# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CorrectIt' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 4.0.0'
  pod 'RxSwift',    '4.3.1'
  pod 'RxCocoa',    '4.3.1'
  pod 'RealmSwift'
  pod 'OpenCV'
  # Pods for CorrectIt

end
